//
// Created by matthew on 3/22/26.
//

#ifndef PYCOMPILE_PYIR_ATTRS_H
#define PYCOMPILE_PYIR_ATTRS_H

#include <mlir/IR/BuiltinAttributes.h>
#include <mlir/IR/Dialect.h>
#include <mlir/IR/DialectImplementation.h>
#include <mlir/IR/OpDefinition.h>
#include <mlir/IR/OpImplementation.h>
#include <llvm/ADT/TypeSwitch.h>

#include "pyir/pyir.h"

// Generated by tablegen
#define GET_ATTRDEF_CLASSES
#include "pyir_attrs.h.inc"
#undef GET_ATTRDEF_CLASSES

#endif //PYCOMPILE_PYIR_ATTRS_H
