FROM fedora:43
RUN dnf install -y git cmake gcc-c++ ninja rpmbuild llvm-devel mlir-devel python3-devel
WORKDIR /build
COPY . .
RUN cmake -B build -DCMAKE_BUILD_TYPE=Release -G Ninja && \
    cmake --build build --target pycompile -j 6 && \
    cd build && \
    cpack -G RPM
